# SPDX-FileCopyrightText: 2026 Will Reed <wreed@disroot.org>
# SPDX-License-Identifier: LGPL-3.0-or-later

version = 1
SPDX-PackageName = "tree-sitter-zenc"
SPDX-PackageSupplier = "Will Reed <wreed@disroot.org>"

[[annotations]]
SPDX-FileCopyrightText = "2026 Will Reed <wreed@disroot.org>"
SPDX-License-Identifier = "LGPL-3.0-or-later"
path = [
    "*.md",
    "*.js",
    "*.json",
    "*.toml",
    "*.mod",
    "*.py",
    "*.swift",
    "*.txt",
    "*.zig",
    "*.zon",
    "*.gyp",
    "*.lock",
    "*.xml",
    ".git*",
    ".version",
    ".editorconfig",
    "Makefile",
    "justfile",
    "src/**",
    "externals/**",
    "queries/**",
    "examples/**",
    "bindings/**"
]
